networks:
  pgnet:
    driver: bridge

volumes:
  pgdata1:
  pgdata2:
  pgdata3:

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --name=etcd0
      - --data-dir=/etcd-data
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://0.0.0.0:2380
      - --initial-cluster-state=new
    ports:
      - "2379:2379"
    networks: [pgnet]

  patroni1:
    image: ghcr.io/zalando/patroni:3.3.2
    container_name: patroni1
    hostname: patroni1
    environment:
      PATRONI_KUBERNETES_USE_CONFIGMAP: "false"
    volumes:
      - ./conf/patroni1.yml:/etc/patroni/patroni.yml:ro
      - pgdata1:/var/lib/postgresql/data
    ports:
      - "8008:8008"
    depends_on: [etcd]
    networks: [pgnet]

  patroni2:
    image: ghcr.io/zalando/patroni:3.3.2
    container_name: patroni2
    hostname: patroni2
    environment:
      PATRONI_KUBERNETES_USE_CONFIGMAP: "false"
    volumes:
      - ./conf/patroni2.yml:/etc/patroni/patroni.yml:ro
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "8009:8008"
    depends_on: [etcd]
    networks: [pgnet]

  patroni3:
    image: ghcr.io/zalando/patroni:3.3.2
    container_name: patroni3
    hostname: patroni3
    environment:
      PATRONI_KUBERNETES_USE_CONFIGMAP: "false"
    volumes:
      - ./conf/patroni3.yml:/etc/patroni/patroni.yml:ro
      - pgdata3:/var/lib/postgresql/data
    ports:
      - "8010:8008"
    depends_on: [etcd]
    networks: [pgnet]

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    depends_on: [patroni1, patroni2, patroni3]
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8404:8404"
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks: [pgnet]